# Generated by Django 5.0.3 on 2024-03-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dob',
            new_name='Customerdob',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='Customerfirstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='Customerlastname',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='card_number',
            new_name='Paymentcard',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='cvv',
            new_name='Paymentcvv',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_id',
            new_name='Paymenttransactionid',
        ),
    ]
