# Generated by Django 5.0.3 on 2024-03-17 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_dob_customer_customerdob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerId',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Paymentid',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
